import "./globals.css";
import { Poppins } from "next/font/google";
import ThemeProvider from "./components/ThemeProvider/ThemeProvider";
import { Header } from "./components/Header/Header";
import { Footer } from "./components/Footer/Footer";
const poppins = Poppins({
  display: "swap",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <body className={poppins.className}>
      <ThemeProvider>
        <Header />
        <main className="min-h-screen">{children}</main>
        <Footer />
      </ThemeProvider>
      <div id="modal-root"></div>
    </body>
  );
}
