import "./globals.css";
import { Poppins } from "next/font/google";
import ThemeProvider from "./components/ThemeProvider/ThemeProvider";
import { Header } from "./components/Header/Header";
import { Footer } from "./components/Footer/Footer";
import { dir } from "i18next";
import { languages } from "../i18n/settings";

const poppins = Poppins({
  display: "swap",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export default function RootLayout({ children, params: { lng } }) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={poppins.className}>
        <ThemeProvider>
          <Header lng={lng} />
          <main className="min-h-screen">{children}</main>
          <Footer />
        </ThemeProvider>
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
