import Section from "../components/Base/Section";

export const metadata = {
  title: "Catalog",
  description: "Generated by create next app",
};

export default function Catalog() {
  return (
    <Section>
      <div className="container">
        <h1>Каталог</h1>
      </div>
    </Section>
  );
}
